name: appsport
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  provider: ^6.1.2
  flutter:
    sdk: flutter

  # Core dependencies
  excel: ^2.0.8
  sqflite: ^2.2.0
  file_picker: ^4.2.7
  path_provider: ^2.0.11
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  flutter_tournament_bracket: ^0.1.0

  # State management (choose one if needed)
  # riverpod: ^3.0.0
  # flutter_riverpod: ^2.4.0

  # HTTP requests and APIs
  http: ^1.1.0
  dio: ^5.3.0

  # Navigation and routing
  go_router: ^9.0.2

  # Animations and UI enhancements
  flutter_slidable: ^0.6.0
  animations: ^2.0.5

  # Localization (for multiple languages)
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_xlsio: ^27.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and code analysis
  flutter_lints: ^4.0.0
  pedantic: ^1.11.1

  # Development tools
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.5
  json_serializable: ^6.8.0

flutter:

  # Ensures that the Material Icons font is included in the application.
  uses-material-design: true

  # Adding assets (images, fonts, etc.)
  assets:
    - assets/images/
    - assets/fonts/

  # Fonts configuration example

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"